### ISSUE TITLE
[Bug]: Plugin override custom Login class

### ISSUE THREAD

**Issue by dangnhdev** [better-futures-studio/filament-local-logins#10]
### What happened?

When use Filament Panel with a custom Login class, this plugin override custom class, caused by hardcode of Filament's default Login class in **LocalLogins** class

```php
class LocalLogins implements Plugin
{
    public function register(Panel $panel): void
    {
        if (! $this->isEnabled($panel->getId())) {
            return;
        }

        $panel
            ->login(LoginPage::class) //should be better if we let user configure this?
            ->renderHook('panels::auth.login.form.before', fn () => view('filament-local-logins::login-buttons'));
    }
}
```
Since this only is a dev plugin, perhaps we could renderHook it directly with the HTML body tag? Apologies, as I'm quite inexperienced with both Filament and PHP, so my suggestions might lack sufficient knowledge.

### How to reproduce the bug

create a custom Login class and register it along with LocalLogins plugin:
```php
class Login extends \Filament\Pages\Auth\Login
{
    public function form(Form $form): Form
    {
        return $form
            ->schema([
                /*$this->getEmailFormComponent(),
                $this->getPasswordFormComponent(),
                $this->getRememberFormComponent(),*/
            ])->extraAttributes([
                'class' => 'hidden',
            ]);
    }
```

### Package Version

1.1.0

### PHP Version

8.2.0

### Laravel Version

11.1.0

### Notes

Note: If you want to override this behaviour now, you can extend Plugins class:
```php
class CustomLocalLogins extends LocalLogins
{
    public function register(Panel $panel): void
    {
        if (! $this->isEnabled($panel->getId())) {
            return;
        }
        $panel->renderHook('panels::auth.login.form.before', fn () => view('filament-local-logins::login-buttons'));
    }
}
```
In your custom Login class add plugin's Trait
```php
class Login extends \Filament\Pages\Auth\Login
{
    use HasLocalLogins; //dev only
    public function form(Form $form): Form
    {
        return .......
    }
```
And register your CustomLocalLogins class instead.

**Comment by KarimAlii** [comment]
@dangnhdev The issue has been fixed in #11, Thanks for your report!
