### ISSUE TITLE
[Bug]: Laravel 11

### ISSUE THREAD

**Issue by Saifallak** [better-futures-studio/filament-local-logins#6]
### What happened?

Cannot use with L11

### How to reproduce the bug

Cannot use with L11

### Package Version

1.0.1

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

Cannot use with L11

**Comment by AbdelElrafa** [comment]
@Saifallak, thanks. We'll work on updating the package to work with Laravel 11.

**Comment by KarimAlii** [comment]
@Saifallak The package has been updated for Laravel 11 compatibility. Thanks for your report!

**Comment by KarimAlii** [comment]
@Saifallak The package has been updated for Laravel 11 compatibility. Thanks for your report!
